### ISSUE TITLE
Not working in India

### ISSUE THREAD

**Issue by xerosanyam** [typpo/textbelt#50] opened 2015-09-14 15:12 UTC
Tried sending text message to following operators:
BSNL Madhya pradesh
Airtel Karnataka
BSNL karanataka

couldn't send to anyone

**Comment by knayan1** [comment] 2016-12-03 08:50
same issue here. :+1:

**Comment by Shashwatsh** [comment] 2017-01-03 03:16
first of all Textbelt does not support BSNL

**Comment by typpo** [comment] 2017-01-29 22:28
Hi all,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I don't have a Indian test number, the paid version should be able to text carriers in your country (I encourage you to try this with the `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:28 UTC

**Comment by Shashwatsh** [comment] 2017-01-29 22:30
Thanks for informing, Let me test this
