### ISSUE TITLE
Send to ATT not working

### ISSUE THREAD

**Issue by kennedto** [typpo/textbelt#91] opened 2016-11-09 17:45 UTC
I get a success message when I send the text, but it never arrives.
How can I debug this.  Is there someway to contact ATT?

**Comment by BarrySmith** [comment] 2016-11-14 04:00
Similar problem

$ curl -X POST http://textbelt.com/text -d number=XXX -d "message=I sent this message for free with textbelt.com"
{
  "success": true
}

Never received it. 

This is a great service, I'd contribute a few dollars to make it run consistently.

**Comment by iprnq9** [comment] 2017-01-14 06:20
Just tested sending myself a message (AT&T). I got a success response from the request but never received the SMS.

Sent my buddy a message (Sprint). I got a success response from the request and he received the SMS.

**Comment by adrianknight89** [comment] 2017-01-28 19:18
I also have the same issue as @iprnq9

**Comment by typpo** [comment] 2017-01-29 19:04
Hi all,

This weekend I made the decision to turn down free service on Textbelt.com.  There is now an option to pay a small amount for an API key.  The paid version reliably texts all carriers within the U.S.  The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers.  If you are able to reproduce this issue after self-hosting, please re-open it.  Thank you!

**Closed by typpo** 2017-01-29 19:04 UTC
