### ISSUE TITLE
Send to P&T Luxembourg not working

### ISSUE THREAD

**Issue by Chrescht** [typpo/textbelt#95] opened 2016-12-01 09:28 UTC
A text sent to a "P&T Luxembourg" number never arrived.
With or without the country prefix.

**Comment by typpo** [comment] 2017-01-29 22:26
Hi Chrescht,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I haven't been able to test Luxembourg, the paid version should reliably text carriers in your country (you can give it a shot with the free `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:26 UTC
