### ISSUE TITLE
Can I help to send SMS to Korea?

### ISSUE THREAD

**Issue by Castar** [typpo/textbelt#82] opened 2016-07-02 11:51 UTC
All of korea Telecom dosen't support This, but I have unlimited SMS Plan.
and I'm using SMSGateway.me, So I can help this project?

**Comment by daluu** [comment] 2016-07-02 18:09
SMSGateway.me wouldn't really help with the intended design of textbelt. However, you could modify/extend textbelt to have an option to use SMSGateway.me. A new configuration setting that when set would have textbelt call SMSGateway.me APIs with a given account defined in the configuration settngs instead of the normal route of trying to send to all the existing SMS gateways (email servers).

This does mean modifying and adding node.js code, if you're comfortable with that.

This would then be used for the self hosting option of textbelt. In practicality, it wouldn't make sense for anyone to contribute their (Android) phone and cellular/SMS plan together with their SMSGateway.me account for the general public to be able to send SMS all over the world through textbelt.com. At a somewhat unpredictable load, one would need a farm of these devices and accounts to handle scale/load for public use.

P.S. one should bug the Korean telecoms to offer SMS gateway support.

**Comment by typpo** [comment] 2017-01-29 22:27
Hi Castar,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I don't have a Korean test number, the paid version should be able to text carriers in your country (I encourage you to try this with the `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:27 UTC
