### ISSUE TITLE
Not receiving text in Telia Denmark

### ISSUE THREAD

**Issue by cowboymathu** [typpo/textbelt#29] opened 2014-11-05 13:52 UTC
Hi,

I just tested with my number to times
    `curl -X POST http://textbelt.com/intl -d number=00454215xxxx -d "message=This is a test msg from textbelt.com"`

but I didn't receive any text. My provider is Telia Denmark (Website says it supports.)

\ Mathu Mou.

**Comment by albertobissacco** [comment] 2015-01-07 11:37
+1

**Comment by bmcustodio** [comment] 2015-02-02 20:04
Same for Vodafone Portugal.

**Comment by me88** [comment] 2015-12-26 14:41
same in switzerland

**Comment by franz-josef-kaiser** [comment] 2016-03-20 12:39
Same in Austria, tested with: 3/Hutchinson and T-Mobile.

**Comment by typpo** [comment] 2017-01-29 22:28
Hi all,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I don't have a Danish/Italian/Portuguese/Swiss/Austrian test number, the paid version should be able to text carriers in all of Europe (I encourage you to try this with the `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:28 UTC
