### ISSUE TITLE
Sent to o2 not working!

### ISSUE THREAD

**Issue by psuet** [typpo/textbelt#103] opened 2016-12-26 08:14 UTC
Hi,

sending a message via your service to o2 doesn't work.

**Comment by typpo** [comment] 2017-01-29 22:25
Hi Paul,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. The paid version should reliably text carriers such as O2. The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:25 UTC
