### ISSUE TITLE
Does not work with Orange France

### ISSUE THREAD

**Issue by gabooh** [typpo/textbelt#15] opened 2014-07-17 09:25 UTC
I've tried with the non interternational number, with 0033 before, with +33 before, none of them work. As Orange is in the list of supported provider, I thought it would work.

Moreover, each time the response was { "success": true }

curl  http://textbelt.com/intl -d number=00336*******\* -d "message=test"

**Comment by Emeric54** [comment] 2016-01-23 15:35
I've the same problem.

**Comment by nemoeric** [comment] 2016-12-16 18:00
same here !

**Comment by typpo** [comment] 2017-01-29 22:29
Hi all,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I don't have a French test number, the paid version should be able to text carriers in all of Europe (I encourage you to try this with the `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:29 UTC
