### ISSUE TITLE
Not working in France

### ISSUE THREAD

**Issue by darkslategrey** [typpo/textbelt#105] opened 2017-01-26 08:57 UTC
With or without the international prefix: 33

Operator: Free mobile

**Comment by typpo** [comment] 2017-01-29 22:25
Hi Gregory,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. The paid version should reliably text carriers within France. The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:25 UTC
