### ISSUE TITLE
Not work for swisscom orange SWITZERLAND

### ISSUE THREAD

**Issue by me88** [typpo/textbelt#62] opened 2015-12-26 14:40 UTC
curl -X POST http://textbelt.com/intl -d number=+4178xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=+4176xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=+4179xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=004178xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=004176xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=004179xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=4178xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=4176xxxxxxx -d "message=Test" 
curl -X POST http://textbelt.com/intl -d number=4179xxxxxxx -d "message=Test" 

All of those give sucess = TRUE  but no sms is sent

**Comment by lcv-idlab** [comment] 2015-12-29 11:04
same problem here.

**Comment by franz-josef-kaiser** [comment] 2016-03-20 12:41
See #29

**Comment by typpo** [comment] 2017-01-29 22:27
Hi guys,

This weekend I made the decision to turn down free service on Textbelt.com. There is now an option to pay a small amount for an API key. Although I don't have a Swiss test number, the paid version should be able to text carriers in your country (I encourage you to try this with the `textbelt_test` key). The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers. If you are able to reproduce this issue after self-hosting, please re-open it. Thank you!

**Closed by typpo** 2017-01-29 22:27 UTC
