### ISSUE TITLE
Unreliable

### ISSUE THREAD

**Issue by andermoran** [typpo/textbelt#84] opened 2016-08-08 21:12 UTC
It sometimes will say it successfully sent but the recipient never receives the text. USA number.

**Comment by daluu** [comment] 2016-08-08 22:18
Maybe the wording needs to be changed. It is "true" that the message was sent successfully from the textbelt/sender side. It of course does not mean the receiver got it successfully (i.e. successfully delivered).

Kind of like snail mail / postal  mail w/o tracking number. It's sent out, but you won't know if it's delivered w/o a tracking number and notification enabled for that tracking number. It could get lost during shipment, etc.

This is why I specifically return this message in my Textbelt (browser extension) client implementations: "Message sent, but see www.textbelt.com for limitations with service." Basically message sent, but with a "caveat" (not 100% guaranteed delivery).

**Comment by typpo** [comment] 2017-01-29 19:05
This weekend I made the decision to turn down free service on Textbelt.com.  There is now an option to pay a small amount for an API key.  The paid version reliably texts all carriers within the U.S.  The free, open-source version in this Github repository is still available for people to self-host.

I'm closing this issue because it applies to the old Textbelt.com, which was continually abused and therefore blocked by many cell providers.  If you are able to reproduce this issue after self-hosting, please re-open it.  Thank you!

**Closed by typpo** 2017-01-29 19:05 UTC

**Comment by tedserreyn** [comment] 2017-01-29 22:11
Given that we haven't seen the free version working with carrriers, how can one trust that you have it working in the paid version,

Ted Serreyn
Serreyn Network Services, LLC

**Comment by typpo** [comment] 2017-01-29 22:24
The new version uses a different transport (actual telephony versus email-to-SMS, which is why it's not free).  As a result, each text sent through the new API has a delivery status that can be checked individually.  This enables you to check whether your text was delivered or not.

You can try sending yourself a text for free with the `textbelt_test` key:

```
$ curl -X POST https://textbelt.com/text \
       --data-urlencode number='5557727420' \
       --data-urlencode message='Hello world' \
       -d key=textbelt_test
```

Also want to point out that before the free version of textbelt.com was overloaded by users, it functioned quite well, which is why it was published in CNET, Linux Journal, several Linux books, etc.  The open source self-hosted version is still an option for those who don't want to pay $3.
